name: test-run
target: modules.train_cascade_stage_c.setup
adaptive_loss_weight: True
clip_text_model_name: "laion/CLIP-ViT-bigG-14-laion2B-39B-b160k"

model_path: 
  # stage_a: /notebooks/sc/stage_a.safetensors
  # stage_b: /notebooks/sc/stage_b_bf16.safetensors
  stage_c: stage_c_bf16.safetensors
  previewer: previewer.safetensors
  effnet: effnet_encoder.safetensors

trainer:
  model_path: ${model_path}
  batch_size: 4
  seed: 1138
  wandb_id: ""
  use_xformers: false
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0

  save_format: safetensors
  checkpoint_dir: checkpoint
  checkpoint_freq: 1
  checkpoint_steps: -1
  save_weights_only: true
  max_epochs: 60
  max_steps: -1

advanced:
  vae_encode_batch_size: 4 # same as batch_size
  train_text_encoder: false
  text_encoder_lr: 3e-6
  
lightning:
  accelerator: gpu
  devices: -1
  precision: bf16-mixed

dataset:
  name: data.arb_dataset.AspectRatioDataset 
  # target_area: 1_048_576 # 1024*1024
  # min_size: 512
  # max_size: 2048
  img_path: "../niji-anime"
  max_token_length: 225 # [75, 150, 225]

optimizer:
  name: bitsandbytes.optim.AdamW8bit
  params:
    lr: 5e-6
    weight_decay: 1e-2

scheduler:
  name: transformers.get_constant_schedule_with_warmup
  params:
    num_warmup_steps: 20
    last_epoch: -1

sampling:
  enabled: true
  use_wandb: true
  seed: 1234
  height: 1280
  width: 768
  every_n_steps: -1
  every_n_epochs: 1
  save_dir: "samples"
  prompts: 
    - "best quality, a girl with a yellow hat and a yellow shirt, sitting, white legwear, uniform, jacket, thighhighs, bare shoulders, high contrast, paint splatter"
    - "best quality, 1girl, solo, loli, cat girl, silver hair ,blue eyes, flat chest, solo, beautiful detailed background, messy hair, long hair"
    - "masterpiece, best quality, 1girl, solo,loli,wedding dress|see-through highleg leotard, veil, elbow gloves, white thighhighs, crown, earrings, bow on waist, sideboob, lace,"
    - "1girl, solo, shirt, thighhighs, skirt, hands on hips, white shirt, crystal, flandre scarlet, blonde hair, grey skirt, red bow, red eyes, black thighhighs, wings, white background,"
    - "1girl,sitting,fantasy,masterpiece,best quality,(long blonde hair),(blue eyes),(floating hair),(black ribbed sweater:1.1),(red plaid skirt:1.1),(cat ears)"
